package:
  name: hexrd
  # requires ".dev" tags following official releases, for now:
  version: {{ environ['GIT_DESCRIBE_TAG'][1:]+environ.get('GIT_DESCRIBE_NUMBER', '') }}

source:
  #git_url: https://github.com/praxes/hexrd.git
  #git_tag: master
  path: ../

build:
  #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  detect_binary_files_with_prefix: true
  osx_is_app: yes
  entry_points:
    - hexrd = hexrd.cli:main

app:
  entry: hexrd
  summary: High-energy x-ray diffraction analysis

requirements:
  build:
    - numpy
    - python
    - setuptools # [win]
  run:
    - matplotlib
    - numba
#    - numbapro
    - numpy
    - progressbar
    - python
    - python.app # [osx]
    - pyyaml
    - scikit-learn
    - scipy
    - wxpython

test:
  imports:
    - hexrd
  commands:
    - hexrd -h
    - hexrd help
    - hexrd find-orientations -h
    - hexrd help find-orientations
    - hexrd fit-grains -h
    - hexrd help fit-grains
    - hexrd gui -h
    - hexrd help gui

about:
  license: LGPL
  home: https://github.com/praxes/hexrd
  summary: High energy diffraction data analysis
