package:
  name: hexrd
  version: master

source:
  git_url: https://github.com/praxes/hexrd.git
  git_tag: master

build:
#  entry_points:
#    - hexrd = hexrd.wx.mainapp:execute
  osx_is_app: yes

requirements:
  build:
    - matplotlib
#    - numbapro
    - numpy #>=1.4.0
    - python
    - scipy >=0.7.0
    - wxpython >=2.8
  run:
    - matplotlib
#    - numbapro
    - numpy #>=1.4.0
    - progressbar
    - python
    - python.app # [osx]
    - scikit-learn
    - scipy >=0.7.0
    - wxpython >=2.8
    - progressbar

test:
  imports:
    - hexrd

about:
  license: LGPL
  home: https://github.com/praxes/hexrd
  summary: High energy diffraction data analysis
