package:
  name: hexrd
  # version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}
  version: {{ GIT_DESCRIBE_TAG }} 
build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  # detect_binary_files_with_prefix: true
  osx_is_app: yes
  entry_points:
    - hexrd = hexrd.cli:main

source:
  # git_url: https://github.com/joelvbernier/hexrd.git
  # git_tag: instrument # edit to point to specific branch or tag
  path: ../

app:
  entry: hexrd gui
  summary: High-energy x-ray diffraction analysis

requirements:
  build:
    - h5py
    - numba
    - numpy ==1.12
    - python
    - setuptools
  run:
    - dill
    - fabio
    - h5py
    - matplotlib
    - numba
    - numpy ==1.12
    - progressbar >=2.3
    - python
    - python.app # [osx]
    - pyyaml
    - qtconsole
    - scikit-learn
    - scikit-image
    - scipy
    - wxpython

test:
  imports:
    - hexrd
  commands:
    - hexrd -V
    - hexrd -h
    - hexrd help
    - hexrd find-orientations -h
    - hexrd help find-orientations
    - hexrd fit-grains -h
    - hexrd help fit-grains
    - hexrd gui -h
    - hexrd help gui
    - hexrd test

about:
  license: LGPL
  home: https://github.com/praxes/hexrd
  summary: High energy diffraction data analysis
