package:
  name: hexrd
  version: master

source:
  git_url: https://github.com/praxes/hexrd.git
  git_tag: master

build:
  osx_is_app: yes
  entry_points:
    - find_orientations = hexrd.indexing.cli:main_find_orientations
    - extract_gvecs = hexrd.peakextraction.cli:main_extract_g_vectors
    - hexrd = hexrd.wx.mainapp:execute

app:
  entry: hexrd
  summary: High-energy x-ray diffraction analysis

requirements:
  build:
    - matplotlib
#    - numba
#    - numbapro
    - numpy #>=1.4.0
    - python
    - scipy >=0.7.0
    - wxpython >=2.8
  run:
    - matplotlib
#    - numba
#    - numbapro
    - numpy #>=1.4.0
    - progressbar
    - python
    - python.app # [osx]
    - pyyaml
    - scikit-learn
    - scipy >=0.7.0
    - wxpython >=2.8

test:
  imports:
    - hexrd
  commands:
    - extract_gvecs -h
    - find_orientations -h

about:
  license: LGPL
  home: https://github.com/praxes/hexrd
  summary: High energy diffraction data analysis
