package:
  name: hexrd
  version: master

source:
  git_url: ../ # if you want to build a particular git commit
  #path: ../ # if you want to build your working directory
  git_rev: master # edit to point to specific branch or tag

build:
  detect_binary_files_with_prefix: true
  osx_is_app: yes
  entry_points:
    - hexrd = hexrd.cli:main

app:
  entry: hexrd gui
  summary: High-energy x-ray diffraction analysis

requirements:
  build:
    - numpy
    - python
    - setuptools
  run:
    - dill
    - matplotlib
    - numba
    - numpy
    - progressbar >=2.3
    - python
    - python.app # [osx]
    - pyyaml
    - qtconsole
    - scikit-learn
    - scipy
    - wxpython

test:
  imports:
    - hexrd
  commands:
    - hexrd -V
    - hexrd -h
    - hexrd help
    - hexrd find-orientations -h
    - hexrd help find-orientations
    - hexrd fit-grains -h
    - hexrd help fit-grains
    - hexrd gui -h
    - hexrd help gui
    - hexrd test

about:
  license: LGPL
  home: https://github.com/praxes/hexrd
  summary: High energy diffraction data analysis
